### ISSUE TITLE
Windows 32/64 bit binaries are missing

### ISSUE THREAD

**Issue by ChessGUI** [ewsandor/flyByKnight#1]
Could you build Windows 32/64 bit binaries of Fly b yKnight 0.3.5 and host these files on you website please? Some years ago, Jim Ablett (who has now retreated from electronic chess)  created a Windows binary here:

http://kirr.homeunix.org/chess/engines/Jim%20Ablett/FLYBYKNIGHT/

**Comment by N1ckn1ght** [comment]
Sadge. Could at least release one, what's the point of always building stuff by yourself when you are not a developer of said program. It could've been fun to test against other engines through xboard.
